server:
  tomcat:
    max-connections: 20000
spring:
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
  redis:
    host: 192.168.1.163 #地址
    port: 6379  # 端口
    jedis:
      pool:
        max-active: 8 #最大连接数
        min-idle: 0 #最小链接
        max-wait: -1ms # 最大等待时间
        max-idle: 8 #最大空闲链接